
import { motion, useScroll, useTransform, useSpring, useMotionTemplate, useMotionValue } from "framer-motion";
import {
  Trophy,
  Zap,
  ArrowRight,
  Code2,
  Users,
  Brain,
  Rocket,
  CheckCircle2,
  Star,
  TrendingUp,
  Award,
  Target,
  Bot,
  Sparkles,
  Play
} from "lucide-react";
import { Button } from "@/components/ui/Button";
import Link from "next/link";
import { useAuth } from "@/lib/hooks/useAuth";
import { usePerformance } from "@/lib/hooks/usePerformance";
import { useRouter } from "next/navigation";
import { useEffect, useState, useRef, MouseEvent } from "react";
import { SplashScreen } from "@/components/ui/SplashScreen";
import { BrandMark } from "@/components/ui/BrandMark";
import { SkillUniverse } from "@/components/landing/SkillUniverse";
import { Marquee } from "@/components/ui/Marquee";
import { Counter } from "@/components/ui/Counter";

// Floating particles component
function FloatingParticles() {
  const particles = Array.from({ length: 50 }, (_, i) => ({
    id: i,
    x: Math.random() * 100,
    y: Math.random() * 100,
    size: Math.random() * 4 + 2,
    duration: Math.random() * 20 + 10,
    delay: Math.random() * 5,
  }));

  return (
    <div className="absolute inset-0 overflow-hidden pointer-events-none">
      {particles.map((particle) => (
        <motion.div
          key={particle.id}
          className="absolute rounded-full bg-gradient-to-r from-accent-indigo/30 to-accent-cyan/30 blur-sm"
          style={{
            left: `${particle.x}%`,
            top: `${particle.y}%`,
            width: particle.size,
            height: particle.size,
          }}
          animate={{
            y: [0, -30, 0],
            x: [0, Math.random() * 20 - 10, 0],
            opacity: [0.2, 0.5, 0.2],
          }}
          transition={{
            duration: particle.duration,
            repeat: Infinity,
            delay: particle.delay,
            ease: "easeInOut",
          }}
        />
      ))}
    </div>
  );
}

// Animated gradient orb
function GradientOrb({ className }: { className?: string }) {
  return (
    <motion.div
      className={`absolute rounded-full blur-3xl ${className}`}
      animate={{
        scale: [1, 1.2, 1],
        opacity: [0.3, 0.5, 0.3],
      }}
      transition={{
        duration: 8,
        repeat: Infinity,
        ease: "easeInOut",
      }}
    />
  );
}

function SpotlightButton({ children, className, ...props }: any) {
  const mouseX = useMotionValue(0);
  const mouseY = useMotionValue(0);

  function handleMouseMove({ currentTarget, clientX, clientY }: MouseEvent) {
    const { left, top } = currentTarget.getBoundingClientRect();
    mouseX.set(clientX - left);
    mouseY.set(clientY - top);
  }

  return (
    <div
      className={`relative group ${className}`}
      onMouseMove={handleMouseMove}
      {...props}
    >
      <motion.div
        className="pointer-events-none absolute -inset-px rounded-xl opacity-0 transition duration-300 group-hover:opacity-100"
        style={{
          background: useMotionTemplate`
            radial-gradient(
              650px circle at ${mouseX}px ${mouseY}px,
              rgba(99, 102, 241, 0.15),
              transparent 80%
            )
          `,
        }}
      />
      {children}
    </div>
  );
}

export default function LandingPage() {
  const router = useRouter();
  const { user, loading } = useAuth();
  const { shouldReduceAnimations } = usePerformance();
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const heroRef = useRef<HTMLDivElement>(null);

  const { scrollYProgress } = useScroll();
  const smoothProgress = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  });

  const opacity = useTransform(smoothProgress, [0, 0.2], [1, 0]);
  const scale = useTransform(smoothProgress, [0, 0.2], [1, 0.8]);
  const heroY = useTransform(smoothProgress, [0, 0.2], [0, 50]);

  useEffect(() => {
    if (!loading && user) {
      router.push("/roadmap");
    }
  }, [user, loading, router]);

  useEffect(() => {
    // Only track mouse on high-performance devices
    if (shouldReduceAnimations) return;

    const handleMouseMove = (e: globalThis.MouseEvent) => {
      setMousePosition({ x: e.clientX, y: e.clientY });
    };
    window.addEventListener("mousemove", handleMouseMove);
    return () => window.removeEventListener("mousemove", handleMouseMove);
  }, [shouldReduceAnimations]);

  if (loading || user) {
    return <SplashScreen />;
  }

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Learning",
      description: "Personalized roadmaps generated by advanced AI tailored to your specific goals and pace.",
      color: "from-pink-500 to-rose-500",
      gradient: "from-pink-500/10 to-rose-500/10",
    },
    {
      icon: Trophy,
      title: "Gamified Progress",
      description: "Earn XP, unlock achievements, and maintain streaks to keep your motivation high.",
      color: "from-amber-500 to-orange-500",
      gradient: "from-amber-500/10 to-orange-500/10",
    },
    {
      icon: Users,
      title: "Community Driven",
      description: "Connect with like-minded learners, join study groups, and share your journey.",
      color: "from-blue-500 to-cyan-500",
      gradient: "from-blue-500/10 to-cyan-500/10",
    },
    {
      icon: Code2,
      title: "Project Based",
      description: "Learn by doing with hands-on projects that build your portfolio as you learn.",
      color: "from-emerald-500 to-green-500",
      gradient: "from-emerald-500/10 to-green-500/10",
    },
  ];

  const stats = [
    { value: 10000, label: "Active Learners", icon: Users, suffix: "+" },
    { value: 500, label: "Skill Paths", icon: Target, suffix: "+" },
    { value: 95, label: "Completion Rate", icon: TrendingUp, suffix: "%" },
    { value: 24, label: "AI Support", icon: Bot, suffix: "/7" },
  ];

  const testimonials = [
    {
      name: "Alex Chen",
      role: "Frontend Developer",
      content: "EDUMATE AI completely transformed how I learn. The AI roadmaps are spot on!",
      avatar: "AC",
      rating: 5,
    },
    {
      name: "Sarah Miller",
      role: "Data Scientist",
      content: "The gamification keeps me addicted to learning. I've never been this consistent.",
      avatar: "SM",
      rating: 5,
    },
    {
      name: "Jordan Taylor",
      role: "UX Designer",
      content: "Finally a platform that adapts to MY learning style. Highly recommended!",
      avatar: "JT",
      rating: 5,
    },
    {
      name: "Mike Johnson",
      role: "Backend Dev",
      content: "The project-based approach is exactly what I needed to build my portfolio.",
      avatar: "MJ",
      rating: 5,
    },
    {
      name: "Emily Davis",
      role: "Product Manager",
      content: "I've tried every platform out there. This is the only one that actually works.",
      avatar: "ED",
      rating: 5,
    },
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-white selection:bg-accent-indigo/30 overflow-hidden font-sans">
      {/* Animated Background - Only on high-performance devices */}
      {!shouldReduceAnimations && (
        <div className="fixed inset-0 pointer-events-none">
          <GradientOrb className="w-[800px] h-[800px] bg-gradient-to-r from-accent-indigo/20 to-accent-violet/20 -top-1/4 -left-1/4" />
          <GradientOrb className="w-[600px] h-[600px] bg-gradient-to-r from-accent-cyan/20 to-blue-500/20 top-1/2 -right-1/4" />
          <GradientOrb className="w-[700px] h-[700px] bg-gradient-to-r from-accent-violet/20 to-pink-500/20 bottom-0 left-1/3" />
          <FloatingParticles />
          <div className="absolute inset-0 bg-[url('/noise.svg')] opacity-[0.03] mix-blend-overlay" />
        </div>
      )}

      {/* Simple gradient background for low-end devices */}
      {shouldReduceAnimations && (
        <div className="fixed inset-0 pointer-events-none bg-gradient-to-br from-accent-indigo/10 via-transparent to-accent-cyan/10" />
      )}

      {/* Navbar */}
      <motion.nav
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        className="fixed top-0 left-0 right-0 z-50 border-b border-white/5 bg-slate-950/80 backdrop-blur-xl supports-[backdrop-filter]:bg-slate-950/60"
      >
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <motion.div whileHover={{ scale: 1.05 }} transition={{ type: "spring", stiffness: 400 }}>
            <BrandMark tagline="Intelligent Skill Engine" size={40} variant="glow" showConnections={!shouldReduceAnimations} />
          </motion.div>
          <div className="flex items-center gap-4">
            <Link href="/login">
              <Button variant="ghost" className="text-slate-300 hover:text-white hover:bg-white/5">
                Log in
              </Button>
            </Link>
            <Link href="/signup">
              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                <Button className="bg-white text-slate-950 hover:bg-slate-200 font-semibold shadow-[0_0_20px_rgba(255,255,255,0.3)] hover:shadow-[0_0_25px_rgba(255,255,255,0.4)] transition-all duration-300">
                  Get Started
                </Button>
              </motion.div>
            </Link>
          </div>
        </div>
      </motion.nav>

      {/* Hero Section */}
      <section ref={heroRef} className="relative min-h-screen flex items-center pt-20 overflow-hidden">
        <motion.div
          style={{ opacity, scale, y: heroY }}
          className="max-w-7xl mx-auto px-6 relative z-10 w-full"
        >
          <div className="grid lg:grid-cols-2 gap-12 lg:gap-20 items-center">
            <div className="text-center lg:text-left order-2 lg:order-1">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 backdrop-blur-md mb-8 hover:bg-white/10 transition-colors cursor-default"
              >
                <Sparkles className="w-4 h-4 text-accent-cyan" />
                <span className="text-sm font-medium text-slate-200">AI-Powered Learning Revolution</span>
              </motion.div>

              <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.1 }}
                className="text-5xl lg:text-7xl font-bold leading-[1.1] mb-6 tracking-tight"
              >
                Master Any Skill <br />
                <span className="relative inline-block">
                  <span className="relative z-10 text-transparent bg-clip-text bg-gradient-to-r from-accent-indigo via-accent-violet to-accent-cyan animate-gradient">
                    Faster Than Ever
                  </span>
                  <motion.span
                    className="absolute -bottom-2 left-0 right-0 h-3 bg-accent-indigo/30 -skew-x-12 blur-sm"
                    initial={{ scaleX: 0 }}
                    animate={{ scaleX: 1 }}
                    transition={{ delay: 0.5, duration: 0.8 }}
                  />
                </span>
              </motion.h1>

              <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.2 }}
                className="text-xl text-slate-400 mb-10 max-w-2xl mx-auto lg:mx-0 leading-relaxed"
              >
                Stop wasting time on generic courses. Get a personalized, AI-generated curriculum that adapts to your goals, pace, and learning style in real-time.
              </motion.p>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.3 }}
                className="flex flex-col sm:flex-row items-center gap-4 justify-center lg:justify-start"
              >
                <Link href="/signup" className="w-full sm:w-auto">
                  <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                    <Button size="lg" className="w-full sm:w-auto text-lg h-14 px-8 bg-gradient-to-r from-accent-indigo to-accent-violet hover:from-accent-indigo/90 hover:to-accent-violet/90 text-white shadow-[0_0_30px_rgba(99,102,241,0.4)] hover:shadow-[0_0_40px_rgba(99,102,241,0.6)] border-0">
                      Start Learning Free
                      <ArrowRight className="w-5 h-5 ml-2" />
                    </Button>
                  </motion.div>
                </Link>
                <Link href="/roadmap" className="w-full sm:w-auto">
                  <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                    <Button size="lg" variant="outline" className="w-full sm:w-auto text-lg h-14 px-8 border-white/10 hover:bg-white/5 hover:border-white/20 backdrop-blur-sm group">
                      <Play className="w-4 h-4 mr-2 fill-current group-hover:text-accent-cyan transition-colors" />
                      View Demo
                    </Button>
                  </motion.div>
                </Link>
              </motion.div>

              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 0.4 }}
                className="mt-12 flex items-center justify-center lg:justify-start gap-8 text-slate-500 text-sm font-medium"
              >
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-accent-cyan" />
                  <span>No credit card required</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-accent-cyan" />
                  <span>Free forever plan</span>
                </div>
              </motion.div>
            </div>

            {/* Interactive Skill Universe */}
            <div className="order-1 lg:order-2 relative h-[500px] lg:h-[600px] w-full flex items-center justify-center perspective-1000">
              <motion.div
                initial={{ opacity: 0, scale: 0.8, rotateX: 20 }}
                animate={{ opacity: 1, scale: 1, rotateX: 0 }}
                transition={{ duration: 1, ease: "easeOut" }}
                className="relative w-full h-full"
              >
                <div className="absolute inset-0 bg-gradient-to-tr from-accent-indigo/20 via-transparent to-accent-cyan/20 rounded-full blur-[100px] animate-pulse" />
                <SkillUniverse />
              </motion.div>
            </div>
          </div>
        </motion.div>

        {/* Scroll Indicator */}
        <motion.div
          className="absolute bottom-10 left-1/2 -translate-x-1/2"
          animate={{ y: [0, 10, 0] }}
          transition={{ duration: 2, repeat: Infinity }}
        >
          <div className="w-6 h-10 rounded-full border-2 border-white/20 flex justify-center p-1">
            <motion.div
              className="w-1 h-2 bg-white/50 rounded-full"
              animate={{ y: [0, 12, 0] }}
              transition={{ duration: 2, repeat: Infinity }}
            />
          </div>
        </motion.div>
      </section>

      {/* Stats Section */}
      <section className="py-20 border-y border-white/5 bg-white/[0.02] relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-6 relative z-10">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                whileHover={{ scale: 1.05, y: -5 }}
                className="text-center group"
              >
                <div className="text-4xl lg:text-5xl font-bold text-white mb-2 bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400 group-hover:from-accent-indigo group-hover:to-accent-cyan transition-all duration-300">
                  <Counter value={stat.value} suffix={stat.suffix} />
                </div>
                <div className="text-slate-400 font-medium group-hover:text-white transition-colors">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-32 relative">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-3xl mx-auto mb-20">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="text-3xl md:text-5xl font-bold mb-6"
            >
              Everything you need to <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-accent-indigo to-accent-cyan">
                Accelerate Your Growth
              </span>
            </motion.h2>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1 }}
              className="text-xl text-slate-400"
            >
              We've combined the best learning techniques with cutting-edge AI to create the ultimate learning experience.
            </motion.p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, index) => (
              <SpotlightButton
                key={feature.title}
                className="h-full"
              >
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className="h-full p-8 rounded-3xl bg-white/[0.02] border border-white/10 hover:border-white/20 transition-all overflow-hidden relative"
                >
                  <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${feature.color} flex items-center justify-center mb-6 shadow-lg group-hover:scale-110 transition-transform duration-300`}>
                    <feature.icon className="w-7 h-7 text-white" />
                  </div>
                  <h3 className="text-xl font-bold text-white mb-3">{feature.title}</h3>
                  <p className="text-slate-400 leading-relaxed">
                    {feature.description}
                  </p>
                </motion.div>
              </SpotlightButton>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-32 bg-slate-900/50 relative overflow-hidden">
        <div className="absolute inset-0 bg-[url('/noise.svg')] opacity-5" />
        <div className="max-w-7xl mx-auto px-6 relative z-10">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-3xl md:text-5xl font-bold text-center mb-16"
          >
            Loved by <span className="text-transparent bg-clip-text bg-gradient-to-r from-accent-indigo to-accent-cyan">Learners</span>
          </motion.h2>

          <Marquee speed={30} pauseOnHover>
            {testimonials.map((item, index) => (
              <div
                key={item.name}
                className="w-[400px] p-8 rounded-3xl bg-slate-950 border border-white/5 hover:border-white/10 relative group transition-all shadow-xl flex-shrink-0"
              >
                <div className="relative z-10">
                  <div className="flex gap-1 mb-6">
                    {[...Array(item.rating)].map((_, i) => (
                      <Star key={i} className="w-5 h-5 text-amber-500 fill-amber-500" />
                    ))}
                  </div>
                  <p className="text-lg text-slate-300 mb-8 leading-relaxed">
                    "{item.content}"
                  </p>
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-accent-indigo to-accent-cyan flex items-center justify-center font-bold text-white shadow-lg">
                      {item.avatar}
                    </div>
                    <div>
                      <div className="font-bold text-white">{item.name}</div>
                      <div className="text-sm text-slate-500">{item.role}</div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </Marquee>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-32 relative overflow-hidden">
        <div className="max-w-5xl mx-auto px-6 relative z-10">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="relative rounded-[2.5rem] overflow-hidden bg-gradient-to-br from-accent-indigo to-accent-violet p-12 md:p-24 text-center group"
          >
            <div className="absolute inset-0 bg-[url('/noise.svg')] opacity-20 mix-blend-overlay" />
            <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_top_right,_var(--tw-gradient-stops))] from-white/20 to-transparent" />

            {/* Animated background shapes */}
            <motion.div
              className="absolute -top-20 -right-20 w-64 h-64 bg-white/10 rounded-full blur-3xl"
              animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0.5, 0.3] }}
              transition={{ duration: 4, repeat: Infinity }}
            />
            <motion.div
              className="absolute -bottom-20 -left-20 w-64 h-64 bg-accent-cyan/20 rounded-full blur-3xl"
              animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0.5, 0.3] }}
              transition={{ duration: 4, repeat: Infinity, delay: 2 }}
            />

            <div className="relative z-10">
              <motion.div
                initial={{ scale: 0 }}
                whileInView={{ scale: 1 }}
                viewport={{ once: true }}
                className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-white/20 backdrop-blur-sm mb-8 shadow-xl"
              >
                <Rocket className="w-10 h-10 text-white" />
              </motion.div>

              <h2 className="text-4xl md:text-6xl font-bold text-white mb-8 tracking-tight">
                Ready to Start Your Journey?
              </h2>
              <p className="text-xl text-indigo-100 mb-12 max-w-2xl mx-auto">
                Join thousands of developers, designers, and creators who are mastering new skills every day.
              </p>
              <Link href="/signup">
                <motion.div
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  <Button size="lg" className="h-16 px-10 text-lg bg-white text-accent-indigo hover:bg-indigo-50 shadow-[0_0_30px_rgba(255,255,255,0.3)] hover:shadow-[0_0_40px_rgba(255,255,255,0.4)] border-0 font-bold">
                    Get Started for Free
                    <ArrowRight className="w-6 h-6 ml-2" />
                  </Button>
                </motion.div>
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 py-12 bg-slate-950 relative">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-6">
          <BrandMark size={36} tagline="Stay Curious" variant="glass" />
          <div className="flex gap-8 text-slate-400 text-sm">
            <a href="#" className="hover:text-white transition-colors">Privacy</a>
            <a href="#" className="hover:text-white transition-colors">Terms</a>
            <a href="#" className="hover:text-white transition-colors">Twitter</a>
            <a href="#" className="hover:text-white transition-colors">GitHub</a>
          </div>
          <div className="text-slate-500 text-sm">
            © 2025 EDUMATE AI. All rights reserved.
          </div>
        </div>
      </footer>

      {/* Custom CSS for gradient animation */}
      <style jsx>{`
        @keyframes gradient {
          0%, 100% {
            background-position: 0% 50%;
          }
          50% {
            background-position: 100% 50%;
          }
        }
        .animate-gradient {
          background-size: 200% 200%;
          animation: gradient 3s ease infinite;
        }
      `}</style>
    </div>
  );
}
